### ISSUE TITLE
Capture Image/Print Image

### ISSUE THREAD

**Issue by ferminjavila** [aparshin/leaflet-GIBS#1]
I tried to add a leaflet control button in order to capture the GIBS map as a PNG image or print the GIBS image using the leaflet print button but I only get the basemap. Any idea?

**Comment by aparshin** [comment]
What plugin have you used to export GIBS layers as PNG? https://github.com/mapbox/leaflet-image?

**Comment by ferminjavila** [comment]
https://github.com/tegansnyder/Leaflet-Save-Map-to-PNG and http://rowanwins.github.io/leaflet-easyPrint/

**Comment by aparshin** [comment]
I failed to test `Leaflet-Save-Map-to-PNG` plugin (can't right now set up local web server to use proxy script). But I've tried [html2canvas v0.4.1](https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js) to generate image from Leaflet's map with GIBS layer - it works fine for me. `Leaflet-Save-Map-to-PNG` uses that library, but a very very old version of it. You can try to update `html2canvas` library inside `Leaflet-Save-Map-to-PNG` plugin, maybe it will solve all the problems...

`easyPrint` plugin works good for me (Win7, Chrome).
